### ISSUE TITLE
changed file name to class-route.php from .lib/next-ferry/routes.php ?

### ISSUE THREAD

**Issue by giorgioriccardi** [enejb/bowen.today#4]
https://github.com/enejb/bowen.today/blob/fa50c59b1a170dafe70451a420a81e0906188256/index.php#L7

a no longer existing file is still referenced: `require_once( 'lib/next-ferry/routes.php' );` but maybe I'm just missing the point. I did not review it thoroughly yet

**Comment by enejb** [comment]
Yeah the index.php file is not really used any more. We can probably delete it.
